# Generated by Django 5.0.3 on 2024-05-23 07:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("apteka", "0001_initial"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="doctor",
            name="tavsiflari_dori",
        ),
        migrations.AddField(
            model_name="doctor",
            name="advices",
            field=models.ManyToManyField(
                blank=True, null=True, related_name="doctors", to="apteka.pill"
            ),
        ),
    ]
