# Generated by Django 5.0.3 on 2024-05-23 07:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("apteka", "0002_remove_doctor_tavsiflari_dori_doctor_advices"),
    ]

    operations = [
        migrations.AlterField(
            model_name="doctor",
            name="advices",
            field=models.ManyToManyField(related_name="doctors", to="apteka.pill"),
        ),
    ]
