# Generated by Django 5.0.3 on 2024-05-23 07:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("apteka", "0003_alter_doctor_advices"),
    ]

    operations = [
        migrations.AddField(
            model_name="type",
            name="name_en",
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AddField(
            model_name="type",
            name="name_ru",
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AddField(
            model_name="type",
            name="name_uz",
            field=models.CharField(max_length=255, null=True),
        ),
    ]
