# Generated by Django 5.0.3 on 2024-05-24 10:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("apteka", "0006_commentary_entry"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="doctor",
            options={"ordering": ["-created_at"]},
        ),
        migrations.AddField(
            model_name="pill",
            name="popular",
            field=models.BooleanField(default=False, verbose_name="ommabopmi?"),
        ),
    ]
