# Generated by Django 5.0.3 on 2024-05-24 11:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("apteka", "0008_remove_pill_category_pill_category"),
    ]

    operations = [
        migrations.DeleteModel(
            name="Rating",
        ),
    ]
