# Generated by Django 5.0.3 on 2024-05-24 11:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("apteka", "0009_delete_rating"),
    ]

    operations = [
        migrations.AddField(
            model_name="pill",
            name="rank",
            field=models.IntegerField(
                choices=[(1, 1), (2, 2), (3, 3), (4, 4), (5, 5)], default=5
            ),
        ),
    ]
