# Generated by Django 5.0.3 on 2024-05-24 11:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("apteka", "0010_pill_rank"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="commentary",
            options={"ordering": ["-published"]},
        ),
        migrations.AlterModelOptions(
            name="pill",
            options={"ordering": ["-published"]},
        ),
        migrations.RenameField(
            model_name="pill",
            old_name="category",
            new_name="categories",
        ),
        migrations.AlterField(
            model_name="pill",
            name="usage_url",
            field=models.URLField(blank=True, max_length=1024, null=True),
        ),
    ]
