# Generated by Django 5.0.3 on 2024-05-25 10:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("apteka", "0013_alter_pill_table"),
    ]

    operations = [
        migrations.AlterField(
            model_name="pill",
            name="categories",
            field=models.ManyToManyField(to="apteka.category"),
        ),
    ]
