# Generated by Django 5.0.3 on 2024-05-27 05:27

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("apteka", "0014_alter_pill_categories"),
    ]

    operations = [
        migrations.AlterField(
            model_name="pill",
            name="categories",
            field=models.ManyToManyField(blank=True, null=True, to="apteka.category"),
        ),
        migrations.AlterField(
            model_name="pill",
            name="type",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="pills",
                to="apteka.type",
            ),
        ),
        migrations.AlterField(
            model_name="pill",
            name="type_en",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="pills",
                to="apteka.type",
            ),
        ),
        migrations.AlterField(
            model_name="pill",
            name="type_ru",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="pills",
                to="apteka.type",
            ),
        ),
        migrations.AlterField(
            model_name="pill",
            name="type_uz",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="pills",
                to="apteka.type",
            ),
        ),
    ]
