# Generated by Django 5.0.3 on 2024-05-27 06:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("apteka", "0015_alter_pill_categories_alter_pill_type_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="pill",
            name="type_en",
        ),
        migrations.RemoveField(
            model_name="pill",
            name="type_ru",
        ),
        migrations.RemoveField(
            model_name="pill",
            name="type_uz",
        ),
    ]
