# Generated by Django 5.0.3 on 2024-05-27 12:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("apteka", "0016_remove_pill_type_en_remove_pill_type_ru_and_more"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="category",
            options={
                "verbose_name": "Kategoriya",
                "verbose_name_plural": "Kategoriyalar",
            },
        ),
        migrations.AlterField(
            model_name="pill",
            name="categories",
            field=models.ManyToManyField(blank=True, to="apteka.category"),
        ),
    ]
