# Generated by Django 5.0.3 on 2024-05-27 13:15

import ckeditor.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("apteka", "0017_alter_category_options_alter_pill_categories"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="achievement",
            options={
                "ordering": ["-id"],
                "verbose_name": "Muvaffaqiyat",
                "verbose_name_plural": "Muvaffaqiyatlar",
            },
        ),
        migrations.AlterModelOptions(
            name="commentary",
            options={
                "ordering": ["-published"],
                "verbose_name": "Izoh",
                "verbose_name_plural": "Izohlar",
            },
        ),
        migrations.AlterModelOptions(
            name="doctor",
            options={
                "ordering": ["-created_at"],
                "verbose_name": "Doktor",
                "verbose_name_plural": "Doktorlar",
            },
        ),
        migrations.AlterModelOptions(
            name="entry",
            options={
                "ordering": ["-created_at"],
                "verbose_name": "Murojat",
                "verbose_name_plural": "Murojatlar",
            },
        ),
        migrations.AlterModelOptions(
            name="partner",
            options={
                "ordering": ["-id"],
                "verbose_name": "Hamkor",
                "verbose_name_plural": "Hamkorlar",
            },
        ),
        migrations.AlterModelOptions(
            name="pill",
            options={
                "ordering": ["-created_at"],
                "verbose_name": "Dori",
                "verbose_name_plural": "Dorilar",
            },
        ),
        migrations.AlterModelOptions(
            name="type",
            options={
                "verbose_name": "Dori turi",
                "verbose_name_plural": "Dori turlari",
            },
        ),
        migrations.AlterField(
            model_name="pill",
            name="body",
            field=ckeditor.fields.RichTextField(
                blank=True, null=True, verbose_name="Dori haqida ma'lumot"
            ),
        ),
        migrations.AlterField(
            model_name="pill",
            name="body_en",
            field=ckeditor.fields.RichTextField(
                blank=True, null=True, verbose_name="Dori haqida ma'lumot"
            ),
        ),
        migrations.AlterField(
            model_name="pill",
            name="body_ru",
            field=ckeditor.fields.RichTextField(
                blank=True, null=True, verbose_name="Dori haqida ma'lumot"
            ),
        ),
        migrations.AlterField(
            model_name="pill",
            name="body_uz",
            field=ckeditor.fields.RichTextField(
                blank=True, null=True, verbose_name="Dori haqida ma'lumot"
            ),
        ),
        migrations.AlterField(
            model_name="pill",
            name="categories",
            field=models.ManyToManyField(
                blank=True, to="apteka.category", verbose_name="Kategoriyalar"
            ),
        ),
        migrations.AlterField(
            model_name="pill",
            name="name",
            field=models.CharField(max_length=255, verbose_name="Nomi"),
        ),
        migrations.AlterField(
            model_name="pill",
            name="name_en",
            field=models.CharField(max_length=255, null=True, verbose_name="Nomi"),
        ),
        migrations.AlterField(
            model_name="pill",
            name="name_ru",
            field=models.CharField(max_length=255, null=True, verbose_name="Nomi"),
        ),
        migrations.AlterField(
            model_name="pill",
            name="name_uz",
            field=models.CharField(max_length=255, null=True, verbose_name="Nomi"),
        ),
        migrations.AlterField(
            model_name="type",
            name="name",
            field=models.CharField(max_length=255, verbose_name="Nomi"),
        ),
        migrations.AlterField(
            model_name="type",
            name="name_en",
            field=models.CharField(max_length=255, null=True, verbose_name="Nomi"),
        ),
        migrations.AlterField(
            model_name="type",
            name="name_ru",
            field=models.CharField(max_length=255, null=True, verbose_name="Nomi"),
        ),
        migrations.AlterField(
            model_name="type",
            name="name_uz",
            field=models.CharField(max_length=255, null=True, verbose_name="Nomi"),
        ),
        migrations.AlterModelTable(
            name="partner",
            table="partners",
        ),
    ]
