# Generated by Django 5.0.3 on 2024-05-28 09:26

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("apteka", "0020_alter_achievement_description_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="achievement",
            name="description",
            field=models.CharField(
                default=django.utils.timezone.now, max_length=255, verbose_name="Matni"
            ),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name="achievement",
            name="description_en",
            field=models.CharField(max_length=255, null=True, verbose_name="Matni"),
        ),
        migrations.AlterField(
            model_name="achievement",
            name="description_ru",
            field=models.CharField(max_length=255, null=True, verbose_name="Matni"),
        ),
        migrations.AlterField(
            model_name="achievement",
            name="description_uz",
            field=models.CharField(max_length=255, null=True, verbose_name="Matni"),
        ),
        migrations.AlterField(
            model_name="achievement",
            name="title",
            field=models.CharField(
                default="Yil brendi 2024", max_length=255, verbose_name="Sarlavhasi"
            ),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name="achievement",
            name="title_en",
            field=models.CharField(
                max_length=255, null=True, verbose_name="Sarlavhasi"
            ),
        ),
        migrations.AlterField(
            model_name="achievement",
            name="title_ru",
            field=models.CharField(
                max_length=255, null=True, verbose_name="Sarlavhasi"
            ),
        ),
        migrations.AlterField(
            model_name="achievement",
            name="title_uz",
            field=models.CharField(
                max_length=255, null=True, verbose_name="Sarlavhasi"
            ),
        ),
    ]
