# Generated by Django 5.0.3 on 2024-05-28 10:01

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("apteka", "0021_alter_achievement_description_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="pill",
            name="expiration_date",
            field=models.DateField(
                default=django.utils.timezone.now, verbose_name="Yaroqlilik muddati"
            ),
            preserve_default=False,
        ),
    ]
