# Generated by Django 5.0.3 on 2024-05-28 10:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("apteka", "0022_pill_expiration_date"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="commentary",
            options={
                "ordering": ["-created_at"],
                "verbose_name": "Izoh",
                "verbose_name_plural": "Izohlar",
            },
        ),
        migrations.RenameField(
            model_name="commentary",
            old_name="published",
            new_name="created_at",
        ),
        migrations.AlterField(
            model_name="commentary",
            name="body",
            field=models.TextField(verbose_name="Izoh"),
        ),
    ]
