# Generated by Django 5.0.3 on 2024-05-28 10:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("apteka", "0023_alter_commentary_options_and_more"),
    ]

    operations = [
        migrations.RenameField(
            model_name="achievement",
            old_name="image",
            new_name="picture",
        ),
        migrations.RenameField(
            model_name="doctor",
            old_name="name",
            new_name="fullname",
        ),
        migrations.RenameField(
            model_name="entry",
            old_name="phonenumber",
            new_name="phone_number",
        ),
        migrations.RenameField(
            model_name="partner",
            old_name="image",
            new_name="picture",
        ),
    ]
