# Generated by Django 5.0.3 on 2024-05-28 10:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("apteka", "0024_rename_image_achievement_picture_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="commentary",
            name="body_en",
            field=models.TextField(null=True, verbose_name="Izoh"),
        ),
        migrations.AddField(
            model_name="commentary",
            name="body_ru",
            field=models.TextField(null=True, verbose_name="Izoh"),
        ),
        migrations.AddField(
            model_name="commentary",
            name="body_uz",
            field=models.TextField(null=True, verbose_name="Izoh"),
        ),
    ]
