# Generated by Django 5.0.3 on 2024-05-28 10:50

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("apteka", "0025_commentary_body_en_commentary_body_ru_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="achievement",
            name="created_at",
            field=models.DateTimeField(
                auto_now_add=True,
                default=django.utils.timezone.now,
                verbose_name="Qo'shilgan vaqt",
            ),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="achievement",
            name="updated_at",
            field=models.DateTimeField(
                auto_now=True, verbose_name="O'zgartirilgan vaqt"
            ),
        ),
    ]
