# Generated by Django 5.0.3 on 2024-05-30 05:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("apteka", "0027_alter_achievement_options"),
    ]

    operations = [
        migrations.AlterField(
            model_name="partner",
            name="picture",
            field=models.ImageField(
                upload_to="partners/photos/", verbose_name="Hamkor logosi"
            ),
        ),
    ]
