# Generated by Django 5.0.3 on 2024-06-05 05:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("apteka", "0028_alter_partner_picture"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="commentary",
            name="body_en",
        ),
        migrations.RemoveField(
            model_name="commentary",
            name="body_ru",
        ),
        migrations.RemoveField(
            model_name="commentary",
            name="body_uz",
        ),
        migrations.AlterField(
            model_name="doctor",
            name="picture",
            field=models.ImageField(upload_to="doctors/photos/", verbose_name="Rasmi"),
        ),
    ]
