# Generated by Django 5.0.3 on 2024-06-10 07:29

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("apteka", "0029_remove_commentary_body_en_remove_commentary_body_ru_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="pill",
            name="picture",
            field=models.ImageField(upload_to="pills/photos/", verbose_name="Rasmi"),
        ),
        migrations.AlterField(
            model_name="pill",
            name="type",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="pills",
                to="apteka.type",
                verbose_name="Dori turi",
            ),
        ),
    ]
